/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.CountryController;
import controllers.RegionController;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.Country;
import models.Region;
import tools.Setting;

/**
 *
 * @author ASUS
 */
public class CountriesView extends javax.swing.JInternalFrame {

    models.Country country = new models.Country();
    CountryController countryController = new CountryController();
    models.Region region = new models.Region();
    RegionController regionController = new RegionController();

    /**
     * Creates new form Country
     */
    public CountriesView() {
        initComponents();
        bindingTabel();
        comboboxRegions();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        bt_add1 = new javax.swing.JButton();
        bt_delete1 = new javax.swing.JButton();
        cmbRegion = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_countries = new javax.swing.JTable();
        t_search = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        cmbCountry = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Country");

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jPanel1.setBackground(new java.awt.Color(0, 204, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Country Details"));

        jLabel1.setText("ID");

        tid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tidMouseClicked(evt);
            }
        });
        tid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tidKeyTyped(evt);
            }
        });

        jLabel2.setText("Name");

        tname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tnameKeyTyped(evt);
            }
        });

        jLabel4.setText("Region");

        bt_add1.setText("SAVE");
        bt_add1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_add1ActionPerformed(evt);
            }
        });

        bt_delete1.setText("Delete");
        bt_delete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_delete1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(164, 252, Short.MAX_VALUE)
                        .addComponent(bt_add1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_delete1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tid, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tname, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbRegion, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tid))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(tname, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbRegion, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_delete1)
                    .addComponent(bt_add1)))
        );

        tbl_countries.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbl_countries.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbl_countriesMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_countries);

        t_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_searchActionPerformed(evt);
            }
        });
        t_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_searchKeyTyped(evt);
            }
        });

        jButton1.setText("SEARCH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cmbCountry.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Name", "Region" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cmbCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t_search, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jButton1))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(t_search)
                        .addComponent(cmbCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_countriesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_countriesMousePressed
        int row = tbl_countries.getSelectedRow();
        tid.setText((String) tbl_countries.getValueAt(row, 0));
        tname.setText((String) tbl_countries.getValueAt(row, 1));
//       tregion_id.setText((String) tbl_countries.getValueAt(row, 2).toString());
        String regionName = (String) tbl_countries.getValueAt(row, 2).toString();
//        JOptionPane.showMessageDialog(this, regionController.selectByName(regionName).getRegionId());
        cmbRegion.setSelectedItem(regionController.selectByName(regionName).getRegionId()+" - "+regionName);

//        int maxItem = cmbRegion.getMaximumRowCount();
//        for (int i = 0; i < maxItem; i++) {
//            String regionId = cmbRegion.getItemAt(i).toString();            
//            String[] getRegionName = regionId.split(" - ");
//            String regName = getRegionName[1];
//            if (regName.equals(regionName)) {
//                cmbRegion.setSelectedIndex(i);
//            }
//        }
        tid.setEnabled(false);
    }//GEN-LAST:event_tbl_countriesMousePressed

    private void t_searchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_searchKeyTyped
//        bindingTabelSearch();
    }//GEN-LAST:event_t_searchKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     String field;
        if (cmbCountry.getSelectedItem().equals("ID")) {
            field="countryId";
        }
        else if (cmbCountry.getSelectedItem().equals("Name")) {
            field = "countryName";
        }
        else{
            field = "regionId.regionName";
        }
        
        String search = t_search.getText();
        DefaultTableModel tableModel = new DefaultTableModel();
        tableModel.setColumnIdentifiers(
                new String[]{
                    "ID",
                    "COUNTRY NAME",
                    "REGION NAME"
                }
        );

        for (Object c : countryController.search("Country", field, search)) {
            country = (Country) c;
            Object[] o = new Object[3];
            o[0] = country.getCountryId();
            o[1] = country.getCountryName();
            o[2] = country.getRegionId().getRegionName();
            tableModel.addRow(o);
        }
        tbl_countries.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tbl_countries.setModel(tableModel);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bt_add1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_add1ActionPerformed
        String id = tid.getText();
        String name = tname.getText();
//        region_id = cmbRegion.getSelectedIndex();

        String regionId = cmbRegion.getSelectedItem().toString();
        String[] getRegionId = regionId.split(" - ");

        JOptionPane.showMessageDialog(this, countryController.save(id, name, getRegionId[0]));
        reset();

//        String a = countryController.selectById(id).getId();
//        if (id.equals(a)) {
//            JOptionPane.showMessageDialog(this, countryController.update(name, Integer.toString(region_id), id));
//
//        } else {
//            JOptionPane.showMessageDialog(this, countryController.create(name, Integer.toString(region_id), id));
//        }
//        reset();
        bindingTabel();
    }//GEN-LAST:event_bt_add1ActionPerformed

    private void bt_delete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_delete1ActionPerformed
        if (JOptionPane.showConfirmDialog(this, "Delete Data?", "Confirmation",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            String id = tid.getText();
            JOptionPane.showMessageDialog(this, countryController.delete(id));
            reset();
            bindingTabel();
        }
    }//GEN-LAST:event_bt_delete1ActionPerformed

    private void t_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_searchActionPerformed

    private void tidMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tidMouseClicked
        reset();
        tid.requestFocus();
    }//GEN-LAST:event_tidMouseClicked

    private void tidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tidKeyTyped
        new Setting().checkAlphabet(evt);
        new Setting().checkLength(tid, 2, evt);
    }//GEN-LAST:event_tidKeyTyped

    private void tnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tnameKeyTyped
       new Setting().checkAlphabet(evt);
    }//GEN-LAST:event_tnameKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_add1;
    private javax.swing.JButton bt_delete1;
    private javax.swing.JComboBox<String> cmbCountry;
    private javax.swing.JComboBox<String> cmbRegion;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField t_search;
    private javax.swing.JTable tbl_countries;
    private javax.swing.JTextField tid;
    private javax.swing.JTextField tname;
    // End of variables declaration//GEN-END:variables
 private void reset() {
        tid.setEnabled(true);
        tid.setText("");
        tname.setText("");

        cmbRegion.setSelectedIndex(0);
    }

    private void bindingTabel() {

        DefaultTableModel tableModel = new DefaultTableModel();
        tableModel.setColumnIdentifiers(
                new String[]{
                    "ID",
                    "COUNTRY NAME",
                    "REGION NAME"
                }
        );
        for (Object c : countryController.getAll()) {
            country = (Country) c;
            Object[] o = new Object[3];
            o[0] = country.getCountryId();
            o[1] = country.getCountryName();
            o[2] = country.getRegionId().getRegionName();
            tableModel.addRow(o);
        }
        tbl_countries.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tbl_countries.setModel(tableModel);
    }

    private void comboboxRegions() {
        for (Object r : regionController.getAll()) {
            region = (Region) r;
            cmbRegion.addItem(region.getRegionId() + " - " + region.getRegionName());
        }
    }
    private void bindingTabelSearch() {

        String search = t_search.getText();
        DefaultTableModel tableModel = new DefaultTableModel();
        tableModel.setColumnIdentifiers(
                new String[]{
                    "ID",
                    "COUNTRY NAME",
                    "REGION NAME"
                }
        );

        for (Object c : countryController.search("Country", title, search)) {
            country = (Country) c;
            Object[] o = new Object[3];
            o[0] = country.getCountryId();
            o[1] = country.getCountryName();
            o[2] = country.getRegionId().getRegionName();
            tableModel.addRow(o);
        }
        tbl_countries.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tbl_countries.setModel(tableModel);
    }

}
